version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: recetas_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contrasena
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network: