# Use a base Java image
FROM openjdk:21-jdk-slim

# Set a working directory inside the container
WORKDIR /app

# Copy the JAR file generated by Spring Boot to the container
COPY target/recetas-0.0.1-SNAPSHOT.jar /app/app.jar

# Expose the port on which the Spring Boot application runs (default is 8080)
EXPOSE 8085

# Run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]